### ISSUE TITLE
Placing a block crashes the world

### ISSUE THREAD

**Issue by LolJohn11** [MehVahdJukaar/carpeted-multi#17]
Carpeted mod seems to be the issue here.
Here's the [crash log](https://bytebin.lucko.me/rNkLfUg0dL).

**Comment by hi4444** [comment]
are you able to place any blocks even

**Comment by LolJohn11** [comment]
True, I can't place any blocks whatsoever.

**Comment by hi4444** [comment]
shold be fixed

**Comment by LolJohn11** [comment]
Thanks for the info, will check once the new 1.19.2 build is released

**Comment by LolJohn11** [comment]
Yes, the fix works with the latest Quark (doesn't work with the older 405 version of Quark, though, but that's okay)
