### ISSUE TITLE
[Forge 1.19.2] [1.7] Blocks insta-break when placed + unable to enter chests with placeable block in main hand

### ISSUE THREAD

**Issue by Nycto97** [MehVahdJukaar/carpeted-multi#19]
Placing blocks while Carpeted 1.7 is installed causes blocks to instantly break when placing.

![2023-10-18_02 17 53](https://github.com/MehVahdJukaar/carpeted/assets/83367226/f432350a-e85b-4001-b118-1be007ba89b3)

I'm also unable to enter previously placed chests while having a placeable block in main hand.

![2023-10-18_02 15 51](https://github.com/MehVahdJukaar/carpeted/assets/83367226/8a623ee3-7ffc-45d5-b462-49c53b3cbd73)

Kind regards,
Nycto

**Comment by hi4444** [comment]
just downgrade to the version before and it fixs
for time being

**Comment by Nycto97** [comment]
That's exactly what I did 😊 just wanted to make a report for the issue

**Comment by Nycto97** [comment]
**Fixed in v1.8**
