### ISSUE TITLE
[Suggestion] connection tweakings

### ISSUE THREAD

**Issue by SebSemos** [MehVahdJukaar/carpeted-multi#22]
Not sure if this would be possible. But in this screenshot I see two minor possible tweaks:
- The stair on the right has a part of the carpet going in the slab and showing on the side.
- The slab on top of the stair could connect the carpet to the stair 

![huge_2024-01-19_03 12 14](https://github.com/MehVahdJukaar/carpeted/assets/89230340/277714e2-3a76-4307-a88d-b5e3e1370e3f)

**Comment by MehVahdJukaar** [comment]
thats weird it shouldnt happen. model is slightly offset so that bit should not be visible

**Comment by SebSemos** [comment]
So, this is sodium breaking things. I'm with latest sodium/indium available for 1.20.1
And this is a directionnal thing. Appear on northen and western faces only.


![huge_2024-01-19_23 56 33](https://github.com/MehVahdJukaar/carpeted/assets/89230340/c0b77cea-dd50-447c-a596-322186a9d415)
![huge_2024-01-19_23 56 55](https://github.com/MehVahdJukaar/carpeted/assets/89230340/a9a5f2ff-93c8-48c2-8c14-525da10f412d)

**Comment by MehVahdJukaar** [comment]
Classic sodium 💀. You might want to report to them. This will likely apply to all models with small offsets like this one

**Comment by SebSemos** [comment]
Yeah, I had a look to sodium issues, and some similar are open, I do'nt expect it to be fixed, we'll see...

I'll mark this as close still, as not on your side :)
