### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Telezhka-the-First** [MehVahdJukaar/carpeted-multi#3]
Crashes upon looking at the carpeted block, immediately. It's possible this is because of incompatibility with Jade, I guess.

Crash log:
[wR4Ev2CDwU.txt](https://github.com/MehVahdJukaar/carpeted/files/10892473/wR4Ev2CDwU.txt)

**Comment by MehVahdJukaar** [comment]
No it's optifine issue. It's incompatible with latest forge. Has been for months now

**Comment by Telezhka-the-First** [comment]
Optifine is too big to neglect it: sadly, I will have to play without your mod for now

**Comment by MehVahdJukaar** [comment]
Be aware than as I've said optifibe is incompatibl with forge. This means that the game might crash if other mods like this one use forge rendering API. This issue has persisted for months and there is even some mod that fixes it on CF. Google optifine. I however suggest to use rubidium as optifine is literally the number one cause of issues with mods
