### ISSUE TITLE
1.21+ Support

### ISSUE THREAD

**Issue by MikeOnDeck** [MehVahdJukaar/carpeted-multi#30]
I just want to say first of all that I really appreciate this mod. It should honestly just be a thing that's implemented in the real game, so thank you for doing a thankless task like this!

In any case, is there any intention of updating this mod to support more current versions of Minecraft?

**Comment by MikeOnDeck** [comment]
Apologies, I just saw that this mod is in fact abandoned and is now merged into the [amendments mod](https://github.com/MehVahdJukaar/amendments) (in case someone else sees this in the future).

**Comment by Keaton42** [comment]
Someone else did see it in the future, thanks!
