### ISSUE TITLE
[Fabric] Carpeted stairs and slabs have weird rendering issues with ConnectedTexturesMod

### ISSUE THREAD

**Issue by ProgrEmily** [MehVahdJukaar/carpeted-multi#6]
The issue specifically is that a wool block appears to render inside the carpeted stair block. Assuming it's something to do with CTM assuming something about the block that isn't actually true, but I wouldn't know what the specific issue is.

**Comment by MehVahdJukaar** [comment]
Can you share a screenshot?

**Comment by ProgrEmily** [comment]
I was about to grab a screenshot, when I thought to update my mods and... that fixed the issue? The thing is, with just CTM installed, the issue wasn't present, so I figure it was a problem with CTM *and* some other rendering mod - checked the usual culprits, iris and the sort, but disabling them didn't solve the issue.

Regardless, the issue seems to have resolved itself some point along the line! Apologies for not thinking of that before sending in an issue report.
